### ISSUE TITLE
Add ability to skip tests

### ISSUE THREAD

**Issue by billychow68** [commander-cli/commander#127]
While developing test cases in Commander, I find it would be useful to be able to skip tests as needed. Maybe there's a better way to do this, but currently, I comment out the entire test case "block" in the YAML.

**Comment by dylanhitt** [comment]
I think this could be dealt with an enabled field: ex. 
```yaml
it should print hello world:
    command: echo hello world
    stdout: hello world
    exit-code: 0
    enabled: false // default is true
```
